# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5078bb15f01c5f0ce7159d6c66b50310"
name = "swapngo"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[app_proxy]
url = "/apps/proxy"
subpath = "swaply"
prefix = "apps"

[pos]
embedded = false
